omniduino:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  wheel1_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor1_shaft_joint
    pid: {p: 0.1, i: 0.0, d: 0.0001}

  wheel2_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor2_shaft_joint
    pid: {p: 0.1, i: 0.0, d: 0.0001}

  wheel3_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor3_shaft_joint
    pid: {p: 0.1, i: 0.0, d: 0.0001}

  wheel4_controller:
    type: velocity_controllers/JointVelocityController
    joint: motor4_shaft_joint
    pid: {p: 0.1, i: 0.0, d: 0.0001}

  sus_controller0:
    type: effort_controllers/JointPositionController
    joint: sus1_joint
    pid: {p: 100, i: 100.0, d: 100, i_clamp: 10.0}
      
  sus_controller1:
    type: effort_controllers/JointPositionController
    joint: sus2_joint
    pid: {p: 100, i: 100.0, d: 100, i_clamp: 10.0}

  sus_controller2:
    type: effort_controllers/JointPositionController
    joint: sus3_joint
    pid: {p: 100, i: 100.0, d: 100, i_clamp: 10.0}

  sus_controller3:
    type: effort_controllers/JointPositionController
    joint: sus4_joint
    pid: {p: 100, i: 100.0, d: 100, i_clamp: 10.0}

  camera_angle_controller:
    type: effort_controllers/JointPositionController
    joint: camera_base_link_joint
    pid: {p: 1.0, i: 0.0, d: 0.0001}